export const projects = [
  {
    id: 0,
    title: 'Lorem ipsum',
    description: 'Nunc ut tellus sed mauris iaculis rhoncus eget sit amet lacus.',
    endTime: Date.now() + Math.floor(Math.random() * 10000),
    keywords: ['demo'],
    fundingRequired: 100,
    fundingRaised: 0,
  },
  {
    id: 1,
    title: 'Suspendisse interdum',
    description: 'Nunc feugiat ipsum vitae ornare consectetur.',
    endTime: Date.now() + Math.floor(Math.random() * 10000),
    keywords: ['demo'],
    fundingRequired: 100,
    fundingRaised: 30,
  },
  {
    id: 2,
    title: 'Cras aliquam',
    description: 'Nunc feugiat ipsum vitae ornare consectetur.',
    endTime: Date.now() + Math.floor(Math.random() * 10000),
    keywords: ['demo'],
    fundingRequired: 101,
    fundingRaised: 70,
  },
  {
    id: 3,
    title: 'Vestibulum aliquet',
    description: 'Morbi eleifend felis id molestie tempus.',
    endTime: Date.now() + Math.floor(Math.random() * 10000),
    keywords: ['demo'],
    fundingRequired: 100,
    fundingRaised: 100,
  },
];

export const categories = [
  { name: 'Art' },
  { name: 'Comics' },
  { name: 'Crafts' },
  { name: 'Dance' },
  { name: 'Design' },
  { name: 'Fashion' },
  { name: 'Film & Video' },
  { name: 'Food' },
  { name: 'Games' },
  { name: 'Journalism' },
  { name: 'Music' },
  { name: 'Photography' },
  { name: 'Publishing' },
  { name: 'Technology' },
  { name: 'Theater' },
];
