export const projects = [
  {
    id: 0,
    title: 'Lorem ipsum',
    description: 'Nunc ut tellus sed mauris iaculis rhoncus eget sit amet lacus.',
    startTime: Date.now() - Math.floor(Math.random() * 10000),
    endTime: Date.now() + Math.floor(Math.random() * 10000),
    keywords: ['demo'],
    amountRequired: 100,
    amountRaised: 0,
  },
  {
    id: 1,
    title: 'Suspendisse interdum',
    description: 'Nunc feugiat ipsum vitae ornare consectetur.',
    startTime: Date.now() - Math.floor(Math.random() * 10000),
    endTime: Date.now() + Math.floor(Math.random() * 10000),
    keywords: ['demo'],
    amountRequired: 100,
    amountRaised: 30,
  },
  {
    id: 2,
    title: 'Cras aliquam',
    description: 'Nunc feugiat ipsum vitae ornare consectetur.',
    startTime: Date.now() - Math.floor(Math.random() * 10000),
    endTime: Date.now() + Math.floor(Math.random() * 10000),
    keywords: ['demo'],
    amountRequired: 101,
    amountRaised: 70,
  },
  {
    id: 3,
    title: 'Vestibulum aliquet',
    description: 'Morbi eleifend felis id molestie tempus.',
    startTime: Date.now() - Math.floor(Math.random() * 10000),
    endTime: Date.now() + Math.floor(Math.random() * 10000),
    keywords: ['demo'],
    amountRequired: 100,
    amountRaised: 100,
  },
];

export const categories = [
  { name: 'Art', projNum: '' },
  { name: 'Comics', projNum: '' },
  { name: 'Crafts', projNum: '' },
  { name: 'Dance', projNum: '' },
  { name: 'Design', projNum: '' },
  { name: 'Fashion', projNum: '' },
  { name: 'Film & Video', projNum: '' },
  { name: 'Food', projNum: '' },
  { name: 'Games', projNum: '' },
  { name: 'Journalism', projNum: '' },
  { name: 'Music', projNum: '' },
  { name: 'Photography', projNum: '' },
  { name: 'Publishing', projNum: '' },
  { name: 'Technology', projNum: '' },
  { name: 'Theater', projNum: '' },
];
